config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :goals, except: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/goal.rb
class Goal < ApplicationRecord
  validates :name, :user_id, presence: true
  validates :goal_status, inclusion: [false, true]
  before_validation :ensure_goal_status

  belongs_to :user

  def complete!
    self.goal_status = true
    self.save
  end

  def ensure_goal_status
    self.goal_status ||= false
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  before_validation :ensure_session_token

  has_many :goals

  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.is_password?(password)
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout!(user)
    user.reset_session_token!
    @current_user = nil
    session[:session_token] = nil
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
    render :new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id if current_user

    if @goal.save
      render :show
    else
      flash[:errors] = ['Your Goal is mediocre, bruh']
      redirect_to new_goal_url
    end
  end

  def edit
    @goal = Goal.find_by(id: params[:id])
    render :edit
  end

  def update
    @goal = Goal.find_by(name: params[:goal][:name])

    if @goal.update_attributes(goal_params)
      render :show
    else
      flash[:errors] = ['Your updated Goal is too mediocre']
      redirect_to goal_url(@goal)
    end
  end

  def destroy
    @goal = Goal.find_by(id: params[:id],)

    if @goal
      @goal.destroy
      redirect_to user_url(@goal.user_id)
    else
      flash[:errors] = ['DON\'T FUCK UP MAH SITE']
      redirect_to users_url
    end
  end

  private

  def goal_params
    params.require(:goal).permit(:name, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ["Invalid Username or Password"]
      redirect_to new_session_url
    end
  end

  def destroy
    if current_user
      logout!(current_user)
      redirect_to users_url
    else
      flash[:errors] = ["DON'T MESS WITH MY WEBSITE"]
      redirect_to users_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def index
    @users = User.all
    render :index
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ["CAN'T CREATE INVALID USER MAN"]
      redirect_to new_user_url
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  def update
    @user = User.find_by(id: params[:id])

    if same_password?(@user) && @user.update_attributes(user_params)
      render :show
    else
      flash[:errors] = ["WRONG PASSWORD YA DUNCE"]
      redirect_to edit_user_url(@user)
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
    render :edit
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def same_password?(user)
    return nil unless user
    user.is_password?(params[:user][:old_pass])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"#{form_authenticity_token}\">".html_safe
  end

end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
<%= render 'shared/errors' %>

<% if action == :new %>
  <% action_url = goals_url %>
<% elsif action == :edit %>
  <% action_url = goal_url(goal) %>
<% end %>

<h1>EDIT GOAL!</h1>

<form action="<%= action_url %>"  method="post">
  <%= auth_token %>

  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="name">Name</label>
  <input id="name" type="text" name="goal[name]" value="<%= goal.name %>">

  <br>

  <label for="body">Description</label>
  <br>
  <textarea name="goal[body]" rows="8" cols="80"><%= goal.body %></textarea>

  <br>

  <input id="Submit" type="submit">
</form>

app/views/goals/edit.html.erb
<%= render 'form', action: :edit, goal: @goal %>

app/views/goals/new.html.erb
<%= render 'form', action: :new, goal: @goal %>

app/views/goals/show.html.erb
<% goal = @goal || Goal.find_by(id: params[:id]) %>
<% user = goal.user %>

<h1> <%= goal.name %> </h1>
<h3> By <%= link_to "#{user.username}", user_url(user) %> </h3>

<br>

<h3>Description:</h3>
<p> <%= goal.body %> </p>

<%= link_to "User Index", users_url %>
<% if goal.user_id == current_user.id %>
  <%= link_to "Edit", edit_goal_url(goal)%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <% if current_user %>
      <h4> Hello there, <%= current_user.username %>! </h4>
      <%= button_to 'Log out', session_url(current_user), method: :delete %>
    <% else %>
      <%= link_to 'Log in', new_session_url %>
      <%= link_to 'Sign up', new_user_url %>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <h3> <%= error %> </h3>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>CHANGE PASSWORD!</h1>

<form action="<%= user_url %>"  method="post">
  <%= auth_token %>

  <input type="hidden" name="_method" value="patch">

  <%= render 'shared/errors' %>

  <label for="old_pass">Old Password</label>
  <input id="old_pass" type="password" name="user[old_pass]" value="">

  <br>

  <label for="password">New Password</label>
  <input id="password" type="password" name="user[password]" value="">

  <br>

  <input id="Submit" type="submit">
</form>

app/views/users/index.html.erb
<%= render 'shared/errors' %>

<h1>Goal Helper</h1>

<br>

<ul>
<% if @users %>
  <% @users.each do |user| %>
    <li><%= link_to "#{user.username}", user_url(user) %></li>
  <% end %>
<% else %>
   <li>No Users...</li>
 <% end %>
<ul>

app/views/users/new.html.erb
<%= render 'shared/errors' %>

<h1>SIGN UP!</h1>

<form action="<%= users_url %>"  method="post">
  <%= auth_token %>
  <label for="username">Username</label>
  <input id="username" type="text" name="user[username]" value="">

  <br>

  <label for="password">Password</label>
  <input id="password" type="password" name="user[password]" value="">

  <br>

  <input id="Submit" type="submit">
</form>

app/views/users/show.html.erb
<% goals = @user.goals %>


<h1> <%= @user.username %>'s userpage </h1>

<%= link_to "Back to User Index", users_url %>

<% if current_user == @user %>
  <%= link_to "Edit Password", edit_user_url %>
<% end %>

<h3> <%= @user.username %>'s Goals</h3>

<% if current_user == @user %>
  <%= link_to "New Goal", new_goal_url %>
<% end %>

<br><br>

<% if goals %>
<table>
  <% goals.each do |goal| %>
  <tr>
    <td> <%= link_to "#{goal.name}", goal_url(goal) %> </td>
    <% if goal.user_id == current_user.id %>
      <td> <%= link_to "Edit", edit_goal_url(goal)%> </td>
      <td> <%= link_to "Delete", goal_url(goal), method: :delete %> </td>
    <% end %>
  </tr>
  <% end %>
</table>
<% end %>